---
- hosts: all
  sudo: true
  vars_files:
    - vars/config.yml
  roles:
     - server
     - git
     - vm
     - nodejs
     - apache
     - mariadb
     - php
     - newrelic
     - xdebug
     - composer
     - app

