---
- debug: msg="{{ nodejs }}"
#- name: Make sure nodejs_version is set correctly.
#  assert:
#    that: nodejs.nodejs_version in [ "0.10", "0.12", "4.x" ]
#
#- name: Add Nodesource apt key.
#  apt_key:
#    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
#    state: present
#
#- name: Add NodeSource repositories for Node.js.
#  apt_repository:
#    repo: "{{ item }}"
#    state: present
#  with_items:
#    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
#    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
#
#- name: Ensure Node.js and npm are installed.
#  apt: "name=nodejs={{ nodejs_version }}.* state=present update_cache=yes"
#
#- name: Install forever (to run Node.js apps).
#  npm: name=forever global=yes state=latest
#  when: nodejs_forever
#
#- name: Install additional defined npm global packages.
#  npm:
#    name: "{{ item.name }}"
#    version: "{{ item.version | default('') }}"
#    global: yes
#    state: latest
#  with_items: nodejs_npm_global_packages