---
vm:
  box: s3than/trusty64
  hostname: vagrant.dev55
  environment: development
  memory: ''
  cpus: ''
  chosen_provider: virtualbox
  ssh:
    forward: '1'
    known_hosts_command: ssh-keyscan -t rsa -T 10
    known_hosts_file: /etc/ssh/ssh_known_hosts
    known_hosts:
    - 104.236.178.120
    - github.com
    - bitbucket.org
  network:
    private_network: 192.168.56.102
    forwarded_port:
      ssh_forward_port:
        host: '9594'
        guest: '22'
      mysql_forward_port:
        host: '9595'
        guest: '3306'
      xdebug_forward_port:
        host: '9003'
        guest: '9001'
  provider:
    virtualbox:
      modifyvm:
        natdnshostresolver1: 'on'
        nictype1: virtio
        nictype2: virtio
        natdnsproxy1: 'on'
  synced_folder:
    project_folder:
      sync_type: sshfs
      host_machine: ./project_files
      guest_machine: /home/vagrant/project_files
      owner: vagrant
      group: www-data
  usable_port_range:
    start: 9000
    stop: 10500
server:
  install: '1'
  packages:
  - htop
  - imagemagick
  - multitail
  - ant
  - xvfb
  - chromium-browser
  timezone: UTC
  locale: en_AU.UTF-8
  swap:
    swap_file_path: /swapfile
    swap_file_size: 1024M
    swappiness: 1
  hosts:
  - url: 127.0.0.1
    name: single-sign-on
    local: '1'
  - url: 192.168.20.21
    name: packages.temando.com
    local: '0'
  - url: 192.168.7.175
    name: webservices.hunterexpress.com.au
    local: '0'
  - url: 192.168.7.175
    name: hunterexpress.com.au
    local: '0'
  - url: 192.168.7.175
    name: farmapi.fastway.org
    local: '0'
  - url: 192.168.7.175
    name: api.fastway.org
    local: '0'
  - url: 192.168.7.175
    name: au.api.fastway.org
    local: '0'
  - url: 192.168.7.175
    name: xmlapi.emea.netdespatch.com
    local: '0'
tmux:
  install: '1'
  repo: ppa:pi-rho/dev
  package: tmux=2.0-1~ppa1~t
  version: '2'
dot_files:
  install: '0'
  dot_files_url: ''
git:
  install: '1'
  email: khoa.tran@temando.com
  user_name: khoa.tran
apache:
  install: '1'
mariadb:
  install: '1'
  root_password: '123'
  database: db
  options:
    bind_address: 0.0.0.0
  users:
  - name: dbuser
    host: '%'
    password: 1234
    priv: '*.*:ALL,GRANT'
  dump: ''
  adminer: '1'
newrelic:
  install: '1'
php:
  install: '1'
  ppa: php5
  ioncube: '1'
  packages:
  - php5-cli
  - php5-curl
  - php-http
  - php5-imagick
  - php5-intl
  - php5-mcrypt
  - php5-mysql
  - php5-redis
  - php5-ssh2
  pecl_with_dependents:
  - package: pecl_http
    package_name: http
    depends_on:
    - package: raphf
      package_name: raphf
      priority: 25
    - package: propro
      package_name: propro
      priority: 30
    priority: 35
xdebug:
  install: '1'
  idekey: PHPSTORM
  remote_enable: 'on'
  remote_mode: req
  remote_port: '9001'
  remote_connect_back: 'on'
  profiler_enable: 'off'
  profiler_enable_trigger: 'on'
  remote_autostart: 'on'
  max_nesting_level: 300
  cli_color: 1
memcached:
  install: '1'
  memcached_user: memcache
  memcached_config_file: /etc/memcached.conf
  memcached_port: 11211
  memcached_listen_ip: 127.0.0.1
  memcached_memory_limit: 64
  memcached_connections: 1024
  memcached_log_file: /var/log/memcached.log
  memcached_log_verbosity: ''
composer:
  install: '1'
  auth: ''
nodejs:
  install: '1'
  nodejs_version: '0.12'
  nodejs_forever: false
  nodejs_npm_global_packages:
  - name: bower
  - name: grunt-cli
