---
- stat: path=/vagrant/provision/files/ssh/id_rsa
  register: private_key_host

- stat: path=/vagrant/provision/files/ssh/id_rsa.pub
  register: public_key_host

- stat: path=/home/vagrant/.ssh/id_rsa
  register: private_key_guest

- stat: path=/home/vagrant/.ssh/id_rsa.pub
  register: public_key_guest

- name: send private key to guest
  command: cp /vagrant/provision/files/ssh/id_rsa /home/vagrant/.ssh/
  when: private_key_host.stat.exists == True and vm.ssh.forward == '0'

- name: send private key to guest
  command: cp /vagrant/provision/files/ssh/id_rsa.pub /home/vagrant/.ssh/
  when: public_key_host.stat.exists == True and vm.ssh.forward == '0'

- file: path=/home/vagrant/.ssh state=directory mode=0700 owner=vagrant group=vagrant

- file: path=/home/vagrant/.ssh/id_rsa.pub mode=0644
  when: public_key_guest.stat.exists == True

- file: path=/home/vagrant/.ssh/id_rsa mode=0600
  when: private_key_guest.stat.exists == True

- file: path=/home/vagrant/.ssh/authorized_keys mode=0600

- command: cat /home/vagrant/.ssh/id_rsa.pub > /home/vagrant/.ssh/authorized_keys
  when: public_key_guest.stat.exists == True

- name: Make sure the known hosts file exists
  file: "path={{ vm.ssh.known_hosts_file }} state=touch"

- name: Check host name availability
  shell: "sudo ssh-keygen -f {{ vm.ssh.known_hosts_file }} -F {{ item }}"
  with_items: vm.ssh.known_hosts
  register: known_host_results

- name: Scan the public key
  shell: "{{ vm.ssh.known_hosts_command}} {{ item.item }} >> {{ vm.ssh.known_hosts_file }}"
  with_items: known_host_results.results
  when: item.stdout == ""
