---
- name: Set the hostname in /etc/hostname
  shell: echo {{ vm.hostname }} > /etc/hostname
  when: vm.hostname is defined

- name: Set the hostname
  shell: hostname {{ vm.hostname }}
  when: vm.hostname is defined

- name: Update /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost {{ vm.hostname }}' owner=root group=root mode=0644
